"""
Tool Executor for Nail Salon AI Assistant

This module executes action plans generated by the planner.
It manages tool execution, data flow between actions, and handles errors.

Tools available:
- resolve_service: Resolve service names using fuzzy matching
- get_services: Get all available services
- get_stylists: Get all stylists
- get_stylist_services: Get services for a specific stylist
- get_available_slots: Find available time slots
- book_appointment: Create a booking
"""

import os
import requests
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
from service_resolver import resolve_service_name
from database import get_all_services, get_all_stylists, get_services_for_stylist


class ToolExecutor:
    """Executes action plans and manages tool interactions."""

    def __init__(self):
        # Backend API configuration
        self.api_base = "http://127.0.0.1:8000"

        # Tool registry - maps action names to functions
        self.tools = {
            "resolve_service": self._resolve_service,
            "get_services": self._get_services,
            "get_stylists": self._get_stylists,
            "get_stylist_services": self._get_stylist_services,
            "get_available_slots": self._get_available_slots,
            "book_appointment": self._book_appointment
        }

        # Context storage for data flow between actions
        self.context = {}

    def execute_plan(self, actions: List[str], intent_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a sequence of actions based on the action plan.

        Args:
            actions (List[str]): Ordered list of actions to execute
            intent_data (Dict[str, Any]): Original intent analysis data

        Returns:
            Dict[str, Any]: Execution results with final state and any errors
        """
        self.context = {
            "intent_data": intent_data,
            "results": {},
            "errors": [],
            "current_action": None
        }

        for action in actions:
            try:
                self.context["current_action"] = action
                print(f"Executing action: {action}")

                # Get the tool function
                if action not in self.tools:
                    raise ValueError(f"Unknown action: {action}")

                tool_func = self.tools[action]

                # Execute the tool
                result = tool_func()

                # Store the result
                self.context["results"][action] = result
                self.context["last_result"] = result

                print(f"✓ Action {action} completed successfully")

            except Exception as e:
                error_msg = f"Action {action} failed: {str(e)}"
                self.context["errors"].append(error_msg)
                print(f"✗ {error_msg}")

                # Continue with next action unless it's critical
                if action in ["book_appointment"]:  # Critical actions
                    break

        return self._format_final_result()

    def _resolve_service(self) -> Dict[str, Any]:
        """Resolve a service name to canonical form."""
        service_name = self.context["intent_data"].get("service")
        if not service_name:
            raise ValueError("No service name provided for resolution")

        resolved = resolve_service_name(service_name)
        if not resolved:
            raise ValueError(f"Could not resolve service: {service_name}")

        # Store resolved service info in context
        self.context["resolved_service"] = resolved
        return resolved

    def _get_services(self) -> List[Dict[str, Any]]:
        """Get all available services."""
        try:
            # Try API first
            resp = requests.get(f"{self.api_base}/services")
            resp.raise_for_status()
            return resp.json()
        except:
            # Fallback to direct database access
            return get_all_services()

    def _get_stylists(self) -> List[Dict[str, Any]]:
        """Get all available stylists."""
        try:
            # Try API first
            resp = requests.get(f"{self.api_base}/stylists")
            resp.raise_for_status()
            return resp.json()
        except:
            # Fallback to direct database access
            return get_all_stylists()

    def _get_stylist_services(self) -> List[Dict[str, Any]]:
        """Get services offered by a specific stylist."""
        # Try to get stylist_id from context or intent data
        stylist_id = None

        # Check if we have a resolved stylist
        stylist_name = self.context["intent_data"].get("stylist")
        if stylist_name:
            # Find stylist by name
            stylists = self.context["results"].get("get_stylists", [])
            for stylist in stylists:
                if stylist["name"].lower() == stylist_name.lower():
                    stylist_id = stylist["id"]
                    break

        if not stylist_id:
            # Use first available stylist as default
            stylists = self.context["results"].get("get_stylists", [])
            if stylists:
                stylist_id = stylists[0]["id"]

        if not stylist_id:
            raise ValueError("No stylist ID available for service lookup")

        try:
            # Try API first
            resp = requests.get(f"{self.api_base}/stylists/{stylist_id}/services")
            resp.raise_for_status()
            return resp.json()
        except:
            # Fallback to direct database access
            return get_services_for_stylist(stylist_id)

    def _get_available_slots(self) -> Dict[str, Any]:
        """Find available time slots for booking."""
        # Get required parameters
        date = self.context["intent_data"].get("date")
        if not date:
            # Default to tomorrow if no date specified
            tomorrow = datetime.now().date() + timedelta(days=1)
            date = tomorrow.strftime("%Y-%m-%d")

        # Get stylist_id and service_id
        stylist_id = None
        service_id = None

        # Try to get stylist_id from intent or context
        stylist_name = self.context["intent_data"].get("stylist")
        if stylist_name:
            stylists = self.context["results"].get("get_stylists", [])
            for stylist in stylists:
                if stylist["name"].lower() == stylist_name.lower():
                    stylist_id = stylist["id"]
                    break

        # Try to get service_id from resolved service
        resolved_service = self.context.get("resolved_service")
        if resolved_service:
            service_id = resolved_service.get("service_id")

        # If we don't have service_id, try to find it from service name
        if not service_id:
            service_name = self.context["intent_data"].get("service")
            if service_name:
                services = self.context["results"].get("get_services", [])
                for service in services:
                    if service["name"].lower() == service_name.lower():
                        service_id = service["id"]
                        break

        # If still no service_id, use the first available service
        if not service_id:
            services = self.context["results"].get("get_services", [])
            if services:
                service_id = services[0]["id"]

        # If still no stylist_id, use the first available stylist
        if not stylist_id:
            stylists = self.context["results"].get("get_stylists", [])
            if stylists:
                stylist_id = stylists[0]["id"]

        if not service_id or not stylist_id:
            raise ValueError("Missing required parameters: service_id or stylist_id")

        # Call the API
        params = {
            "date": date,
            "stylist_id": stylist_id,
            "service_id": service_id
        }

        resp = requests.get(f"{self.api_base}/available-slots", params=params)
        resp.raise_for_status()
        return resp.json()

    def _book_appointment(self) -> Dict[str, Any]:
        """Create a new appointment booking."""
        # Get all necessary information from context
        intent_data = self.context["intent_data"]
        resolved_service = self.context.get("resolved_service", {})
        available_slots = self.context["results"].get("get_available_slots", {})
        stylists = self.context["results"].get("get_stylists", [])

        # Extract booking parameters
        client_name = "AI Assistant Test User"  # Would come from user input in real scenario

        # Get service_id from resolved service
        service_id = resolved_service.get("service_id")
        if not service_id:
            raise ValueError("No service_id available for booking")

        # Get stylist_id - prefer specified stylist, otherwise use first available
        stylist_id = None
        stylist_name = intent_data.get("stylist")
        if stylist_name:
            for stylist in stylists:
                if stylist["name"].lower() == stylist_name.lower():
                    stylist_id = stylist["id"]
                    break

        if not stylist_id and stylists:
            stylist_id = stylists[0]["id"]

        if not stylist_id:
            raise ValueError("No stylist_id available for booking")

        # Get date
        date = intent_data.get("date") or available_slots.get("date")
        if not date:
            from datetime import datetime
            date = (datetime.now().date() + timedelta(days=1)).strftime("%Y-%m-%d")

        # Get first available slot
        slots = available_slots.get("slots", [])
        if not slots:
            raise ValueError("No available slots for booking")

        start_time = slots[0]["start"]
        end_time = slots[0]["end"]

        # Prepare booking payload
        payload = {
            "client_name": client_name,
            "stylist_id": stylist_id,
            "service_id": service_id,
            "start_time": start_time,
            "end_time": end_time,
            "date": date
        }

        print(f"Booking payload: {payload}")  # Debug

        # Make the booking
        resp = requests.post(f"{self.api_base}/book", json=payload)
        resp.raise_for_status()
        return resp.json()

    def _format_final_result(self) -> Dict[str, Any]:
        """Format the final execution result."""
        return {
            "success": len(self.context["errors"]) == 0,
            "results": self.context["results"],
            "errors": self.context["errors"],
            "final_context": self.context
        }


def execute_actions(actions: List[str], intent_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convenience function to execute an action plan.

    Args:
        actions (List[str]): List of actions to execute
        intent_data (Dict[str, Any]): Intent analysis data

    Returns:
        Dict[str, Any]: Execution results
    """
    executor = ToolExecutor()
    return executor.execute_plan(actions, intent_data)


# Example usage
if __name__ == "__main__":
    # Test the tool executor
    test_intent = {
        "intent": "ask_services",
        "service": None,
        "date": None,
        "stylist": None,
        "confidence": 0.9
    }

    actions = ["get_services"]
    result = execute_actions(actions, test_intent)

    print("Execution Result:")
    print(f"Success: {result['success']}")
    print(f"Results: {result['results']}")
    if result['errors']:
        print(f"Errors: {result['errors']}")